name: Release

on:
  push:
    tags: ['*']

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Publish package
        env:
          NPM_CONFIG_TOKEN: ${{ secrets.NPM_CONFIG_TOKEN }}
        run: bun publish --access public
