name: Update all versions

on:
  # schedule:
  #   - cron: "0 14 * * *"
  workflow_dispatch:

jobs:
  update-all-files:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "22"
          registry-url: "https://registry.npmjs.org"

      - name: Install environment
        id: install-environment
        run: |
          npm ci
          npm i baseline-browser-mapping@latest

      - name: Run update-all-files
        id: update-all-files
        run: |
          npm run update-widely-available
          if [[ -n "$(git diff)" ]]; then
            echo "changes-available=TRUE" >> $GITHUB_OUTPUT
          else
            echo "changes-available=FALSE" >> $GITHUB_OUTPUT
            echo "no changes made, ending workflow"
          fi

      - name: Commit changed files
        if: steps.update-all-files.outputs.changes-available == 'TRUE'
        id: commit-changed-files
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add .
          git commit -m 'Updating Baseline versions'

      - name: Update patch version
        if: steps.commit-changed-files.outcome == 'success'
        id: update-patch-version
        run: |
          npm version patch
          NODE_VERSION=$(node -p -e "require('./package.json').version")
          git commit -m "Updating version to v$NODEVERSION"

      - name: Update tag and push to main
        if: steps.update-patch-version.outcome == 'success'
        id: update-tag-and-push-to-main
        run: |
          git tag v0.0.0 && git push origin --tags
